/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const LocalSvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny">;
          default: string;
          required: true;
      };
  }>>, {
      name: "icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny";
  }>;
  export const svgNames: ["icon-empty-default", "icon-empty-error", "icon-empty-network", "icon-empty-search", "icon-forbidden", "icon-logo", "icon-moon", "icon-not-found", "icon-server-error", "icon-sun-moon", "icon-sunny"];
  export type SvgName = "icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny";
  export default LocalSvgIcon;
}
