/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(tabbar)': RouteRecordInfo<
      '/(tabbar)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(tabbar)/'
      | '/(tabbar)/example'
      | '/(tabbar)/home'
      | '/(tabbar)/mine'
    >,
    '/(tabbar)/': RouteRecordInfo<
      '/(tabbar)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(tabbar)/example': RouteRecordInfo<
      '/(tabbar)/example',
      '/example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(tabbar)/home': RouteRecordInfo<
      '/(tabbar)/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(tabbar)/mine': RouteRecordInfo<
      '/(tabbar)/mine',
      '/mine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/forgot-password': RouteRecordInfo<
      '/(auth)/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/sign-in': RouteRecordInfo<
      '/(auth)/sign-in',
      '/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/sign-up': RouteRecordInfo<
      '/(auth)/sign-up',
      '/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings': RouteRecordInfo<
      '/(authenticated)/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/403': RouteRecordInfo<
      '/(errors)/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/404': RouteRecordInfo<
      '/(errors)/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/500': RouteRecordInfo<
      '/(errors)/500',
      '/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/example/echarts': RouteRecordInfo<
      '/example/echarts',
      '/example/echarts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/example/icon': RouteRecordInfo<
      '/example/icon',
      '/example/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/example/mock': RouteRecordInfo<
      '/example/mock',
      '/example/mock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(tabbar).vue': {
      routes:
        | '/(tabbar)'
        | '/(tabbar)/'
        | '/(tabbar)/example'
        | '/(tabbar)/home'
        | '/(tabbar)/mine'
      views:
        | 'default'
    }
    'src/pages/(tabbar)/index.vue': {
      routes:
        | '/(tabbar)/'
      views:
        | never
    }
    'src/pages/(tabbar)/example.vue': {
      routes:
        | '/(tabbar)/example'
      views:
        | never
    }
    'src/pages/(tabbar)/home.vue': {
      routes:
        | '/(tabbar)/home'
      views:
        | never
    }
    'src/pages/(tabbar)/mine.vue': {
      routes:
        | '/(tabbar)/mine'
      views:
        | never
    }
    'src/pages/(auth)/forgot-password.vue': {
      routes:
        | '/(auth)/forgot-password'
      views:
        | never
    }
    'src/pages/(auth)/sign-in.vue': {
      routes:
        | '/(auth)/sign-in'
      views:
        | never
    }
    'src/pages/(auth)/sign-up.vue': {
      routes:
        | '/(auth)/sign-up'
      views:
        | never
    }
    'src/pages/(authenticated)/settings.vue': {
      routes:
        | '/(authenticated)/settings'
      views:
        | never
    }
    'src/pages/(errors)/403.vue': {
      routes:
        | '/(errors)/403'
      views:
        | never
    }
    'src/pages/(errors)/404.vue': {
      routes:
        | '/(errors)/404'
      views:
        | never
    }
    'src/pages/(errors)/500.vue': {
      routes:
        | '/(errors)/500'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/example/echarts.vue': {
      routes:
        | '/example/echarts'
      views:
        | never
    }
    'src/pages/example/icon.vue': {
      routes:
        | '/example/icon'
      views:
        | never
    }
    'src/pages/example/mock.vue': {
      routes:
        | '/example/mock'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
